version: '3.1'
services:
  main:
    image: phyremaster/papermc
    container_name: minecraft
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 8192:8192
      - 25565:25565
      - 3303:3303
    volumes:
      - ./data:/papermc
    environment:
      MC_VERSION: 1.16.5
      MC_RAM: "8G"
