version: '3.1'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27015:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
