version: '3.1'
services:
  influxdb:
    image: "influxdb:latest"
    container_name: "influxdb"
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=<username>
      - DOCKER_INFLUXDB_INIT_PASSWORD=<password>
      - DOCKER_INFLUXDB_INIT_ORG=<organisation name>
      - DOCKER_INFLUXDB_INIT_BUCKET=<default bucket>
